2021/01/16 14:39:32 : categories_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 389, in convert_category_export
    category_data['active'] = True if category['active']=='1' else False
KeyError: 'active'

2021/01/16 14:39:33 : categories_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 389, in convert_category_export
    category_data['active'] = True if category['active']=='1' else False
KeyError: 'active'

