2021/01/16 14:44:12 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 665, in storage_data
    getattr(self.get_source_cart(), 'finish_storage_data')()
  File "/opt/lampp/htdocs/v32/cartmigration/models/basecart.py", line 3929, in finish_storage_data
    folder_upload = self.get_folder_upload(self._migration_id)
  File "/opt/lampp/htdocs/v32/cartmigration/models/basecart.py", line 3941, in get_folder_upload
    folder_upload = root_path + '/' + DIR_UPLOAD + '/' + get_config_ini('src', 'file', file = 'test.ini')
TypeError: must be str, not NoneType

2021/01/16 14:45:03 : categories_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 5: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 6: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 7: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 8: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 9: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 10: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 11: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 12: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:03 : categories_errors 13: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 14: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 15: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 16: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 17: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 19: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 20: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 22: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/16 14:45:04 : categories_errors 23: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 390, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

