2021/01/18 09:19:01 : categories_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:23:23 : categories_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:23:35 : categories_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:23:40 : categories_errors 5: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:23:42 : categories_errors 6: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:23:44 : categories_errors 7: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:24:11 : categories_errors 8: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:24:16 : categories_errors 9: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:24:19 : categories_errors 10: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:24:21 : categories_errors 11: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:24:23 : categories_errors 12: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:34:48 : categories_errors 13: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:34:59 : categories_errors 14: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:35:03 : categories_errors 15: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:35:06 : categories_errors 16: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:36:39 : categories_errors 17: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:36:41 : categories_errors 19: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:36:42 : categories_errors 20: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:36:42 : categories_errors 22: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

2021/01/18 09:36:42 : categories_errors 23: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 387, in convert_category_export
    img = get_row_from_list_by_field(categories_ext['data']['cate_imgs'],'cat_id', category['id'])
KeyError: 'cate_imgs'

