2021/01/18 10:43:56 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 665, in storage_data
    getattr(self.get_source_cart(), 'finish_storage_data')()
  File "/opt/lampp/htdocs/v32/cartmigration/models/basecart.py", line 3929, in finish_storage_data
    folder_upload = self.get_folder_upload(self._migration_id)
  File "/opt/lampp/htdocs/v32/cartmigration/models/basecart.py", line 3941, in get_folder_upload
    folder_upload = root_path + '/' + DIR_UPLOAD + '/' + get_config_ini('src', 'file', file = 'test.ini')
TypeError: must be str, not NoneType

2021/01/18 10:45:55 : categories_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:55 : categories_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:55 : categories_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:55 : categories_errors 5: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:56 : categories_errors 6: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:56 : categories_errors 7: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:56 : categories_errors 8: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:57 : categories_errors 9: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:57 : categories_errors 10: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:58 : categories_errors 11: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:58 : categories_errors 12: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:58 : categories_errors 13: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:59 : categories_errors 14: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:59 : categories_errors 15: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:45:59 : categories_errors 16: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:46:00 : categories_errors 17: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:46:00 : categories_errors 19: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:46:00 : categories_errors 20: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:46:01 : categories_errors 22: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

2021/01/18 10:46:01 : categories_errors 23: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

