2021/01/20 10:16:27 : orders_errors 1: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1150, in convert_order_export
    billing_name = self.get_name_from_string(order['bill_fname'] + ' '+ order['bill_lname'])
KeyError: 'bill_fname'

2021/01/20 10:16:36 : orders_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1150, in convert_order_export
    billing_name = self.get_name_from_string(order['bill_fname'] + ' '+ order['bill_lname'])
KeyError: 'bill_fname'

