2021/01/20 12:03:59 : orders_errors 1: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1167, in convert_order_export
    billing_country = get_row_from_list_by_field(orders_ext['data']['countries'], 'countries_name', order['billing_country'])
KeyError: 'countries'

2021/01/20 13:43:38 : orders_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1167, in convert_order_export
    billing_country = get_row_from_list_by_field(orders_ext['data']['countries'], 'countries_name', order['billing_country'])
KeyError: 'countries'

