2021/01/14 17:22:04 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 380, in setup_cart
    setup_target = self.setup_target(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 514, in setup_target
    display_setup_target = getattr(self.target_cart, 'display_setup_target')(data)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 54, in display_setup_target
    api_shop = self.api('shop.json')
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/shopify.py", line 3700, in api
    api_password = self._notice[self._type]['config']['api']['password'] if self._notice[self._type]['config']['api'].get('password') else self._notice[self._type]['config']['api'].get('token')
AttributeError: 'str' object has no attribute 'get'

2021/01/15 15:56:12 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb45dfbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/15 15:56:22 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb45dfb70>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/15 15:56:32 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbb45dfbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/16 14:32:49 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 494
    }
    ^
SyntaxError: invalid syntax

2021/01/16 14:34:26 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 494
    }
    ^
SyntaxError: invalid syntax

2021/01/16 14:43:37 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4dc95f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/16 14:43:47 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4dc94acc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/16 14:43:57 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4dc95f240>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/18 11:20:13 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a8ccc31d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/18 11:20:23 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a8cc71cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/18 11:20:33 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a8ccc3240>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/19 10:31:58 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 945
    customer_data['updated_at'] = customer_info['customers_info_date_account_last_modified']
                                                                                           ^
TabError: inconsistent use of tabs and spaces in indentation

2021/01/19 10:32:09 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 945
    customer_data['updated_at'] = customer_info['customers_info_date_account_last_modified']
                                                                                           ^
TabError: inconsistent use of tabs and spaces in indentation

2021/01/20 10:49:41 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f78468bdf28>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 10:49:51 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7846792b00>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:36:20 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a49b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:36:30 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a4940>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:36:40 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a49b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:36:50 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a4940>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:37:00 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a49b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/20 11:37:10 : Error Connecting:HTTPSConnectionPool(host='quockhai21103.myshopify.com', port=443): Max retries exceeded with url: /admin/api/2021-01/shop.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e882a4940>: Failed to establish a new connection: [Errno -2] Name or service not known',)) : False
2021/01/21 11:58:32 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1262
    order_items.append(order_item)
    ^
IndentationError: unexpected indent

2021/01/21 11:58:45 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1262
    order_items.append(order_item)
    ^
IndentationError: unexpected indent

2021/01/21 11:58:51 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1262
    order_items.append(order_item)
    ^
IndentationError: unexpected indent

2021/01/21 17:20:59 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:21:31 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:25:37 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:29:11 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:30:32 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:30:42 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/21 17:32:20 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
AttributeError: 'NoneType' object has no attribute 'set_notice'

2021/01/22 11:19:49 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 3601
    'user_pass': convert['password']
              ^
SyntaxError: invalid syntax

2021/01/22 16:12:45 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 3412
    'tax_class': 'convert['tax']['code'],
                             ^
SyntaxError: invalid syntax

2021/01/25 09:34:23 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 2256
    }
    ^
SyntaxError: invalid syntax

2021/01/25 11:22:44 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 367
    'products_to_categories': {
                           ^
SyntaxError: invalid syntax

2021/01/26 09:34:21 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 276, in setup_source
    cart_url = getattr(self.get_source_cart(), 'format_url')(request['src_cart_url'])
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 93, in get_source_cart
    self.source_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 496
    'query': "SELECT * FROM _DBPRF_products_to_categories WHERE products_id ODER BY products_id,
                                                                                               ^
SyntaxError: EOL while scanning string literal

2021/01/26 13:45:16 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 4187
    }
    ^
SyntaxError: invalid syntax

2021/01/26 17:48:33 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 4254
    }
    ^
SyntaxError: invalid syntax

2021/01/27 09:22:02 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 4259
    for i in
           ^
SyntaxError: invalid syntax

2021/01/27 10:42:44 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 4270
    }
    ^
SyntaxError: invalid syntax

2021/01/28 12:01:45 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 4159
    for i in
           ^
SyntaxError: invalid syntax

2021/01/28 14:35:31 : Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 348, in setup_cart
    setup_source = self.setup_source(data)
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 284, in setup_source
    getattr(self.get_target_cart(), 'set_notice')(self._notice)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/base_controller.py", line 115, in get_target_cart
    self.target_cart = get_model(cart_name)
  File "/opt/lampp/htdocs/v32/cartmigration/libs/utils.py", line 97, in get_model
    module_class = importlib.import_module(model_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/woocommerce.py", line 3742
    }
    ^
SyntaxError: invalid syntax

