2021/01/18 10:36:38 : categories_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:39 : categories_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:39 : categories_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:39 : categories_errors 5: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:40 : categories_errors 6: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:40 : categories_errors 7: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:40 : categories_errors 8: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:40 : categories_errors 9: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:41 : categories_errors 10: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:41 : categories_errors 11: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:41 : categories_errors 12: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:42 : categories_errors 13: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:42 : categories_errors 14: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:42 : categories_errors 15: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:43 : categories_errors 16: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:43 : categories_errors 17: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1499, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:43 : categories_errors 19: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:44 : categories_errors 20: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:44 : categories_errors 22: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

2021/01/18 10:36:44 : categories_errors 23: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 400, in convert_category_export
    category_data['name'] = category['name']
KeyError: 'name'

