2021/01/20 11:52:18 : orders_errors 1: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1168, in convert_order_export
    billing_state = get_row_from_list_by_field(orders_ext['data']['zones'], 'code', order[
KeyError: 'zones'

2021/01/20 11:52:21 : orders_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1168, in convert_order_export
    billing_state = get_row_from_list_by_field(orders_ext['data']['zones'], 'code', order[
KeyError: 'zones'

