2021/01/21 10:59:51 : orders_errors 1: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 5: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 6: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 7: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

2021/01/21 10:59:51 : orders_errors 8: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1121, in convert_order_export
    order_customer['first_name'] = order['khai2110']
KeyError: 'khai2110'

