2021/01/21 09:25:21 : orders_errors 1: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1221, in convert_order_export
    order_products = get_list_from_list_by_field(orders_ext['data']['orders_items'], 'orders_id', order['orders_id'])
KeyError: 'orders_items'

2021/01/21 09:25:27 : orders_errors 2: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1221, in convert_order_export
    order_products = get_list_from_list_by_field(orders_ext['data']['orders_items'], 'orders_id', order['orders_id'])
KeyError: 'orders_items'

2021/01/21 09:25:31 : orders_errors 3: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1221, in convert_order_export
    order_products = get_list_from_list_by_field(orders_ext['data']['orders_items'], 'orders_id', order['orders_id'])
KeyError: 'orders_items'

2021/01/21 09:25:39 : orders_errors 4: Traceback (most recent call last):
  File "/opt/lampp/htdocs/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/opt/lampp/htdocs/v32/cartmigration/models/cart/custom.py", line 1221, in convert_order_export
    order_products = get_list_from_list_by_field(orders_ext['data']['orders_items'], 'orders_id', order['orders_id'])
KeyError: 'orders_items'

